
api_version = "2023-10"

[[extensions]]
type = "ui_extension"
name = "Checkout- Estimated shipping time"
handle = "checkout-estimated-shipping"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
api_access = true
# network_access = true

# [extensions.settings]
# [[extensions.settings.fields]]
# key = "banner_title"
# type = "single_line_text_field"
# name = "Banner title"
# description = "Enter a title for the banner"

[extensions.settings]
  [[extensions.settings.fields]]
   key = "enable_shipping_time"
   type = "single_line_text_field"
   name = "Show or Hide Shipping Text"
    [[extensions.settings.fields.validations]] 
    name = "choices"
    value = "[\"Show\", \"Hide\"]"
    
   [[extensions.settings.fields]]
   key = "estimated_shipping_heading1"
   type = "single_line_text_field"
   name = "Heading"

    [[extensions.settings.fields]]
    key = "estimated_shipping_list_item1"
    type = "multi_line_text_field"
    name = "List Item"

    [[extensions.settings.fields]]
    key = "estimated_shipping_list_item2"
    type = "multi_line_text_field"
    name = "List Item"

    [[extensions.settings.fields]]
    key = "estimated_shipping_list_item3"
    type = "multi_line_text_field"
    name = "List Item"

    [[extensions.settings.fields]]
    key = "estimated_shipping_textbox1"
   type = "multi_line_text_field"
   name = "Text Box"

    [[extensions.settings.fields]]
   key = "estimated_shipping_heading2"
   type = "single_line_text_field"
   name = "Heading"

    [[extensions.settings.fields]]
    key = "estimated_shipping_textbox2"
   type = "multi_line_text_field" 
   name = "Text Box"
 